server {
    listen 80;
    resolver 169.254.169.253 valid=10s ipv6=off;
    # Serve static files
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy API requests to backend
    location /api/ {
	    #proxy_pass http://backend:3000;
	set $backend "backend.escworkshop.local:3000";
	proxy_pass http://$backend;
	#proxy_pass http://host.docker.internal:3000; # Local backend
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

}
